export enum Page {
    COLLECT = '/collect',
    ACCOUNT = '/account',
    COLLECTION = '/collection',
    DASHBOARD = '/dashboard',
    RANKING = '/ranking',
    SCANNER = '/scanner',
    FAQ = '/faq',
    RULEBOOK = '/rulebook',
    GUILD = '/guild',
    MAIN = '/',
    LOGIN = '/auth/login',
    LOGIN_EMAIL = '/auth/login-email',
    REGISTER = '/auth/register',
    REGISTER_EMAIL = '/auth/register-email',
    ACCOUNT_SETUP = '/auth/account-setup',
    ADMIN_EDIT_CARD = '/admin/edit-card',
    ADMIN_CARDS = '/admin/cards',
    ADMIN_RECENTLY_COLLECTED = '/admin/recently-collected'
}
