/* eslint-disable max-len */
import { Card, CardTier, CardTierValue } from '../types/card';

// '3M3SJZDVFV',
// '3U1XSSBMNF',
// '3X8RN3R4MS',
// '3ZMQQLLWWX',
// '4GYYPTLSYH',
// '4J6KBCCHW1',
// '5DEYQBVWBP',
// '6KVTS4ZFKC',
// '6PZJA4AGP3',
// '6U9U4RUMK6',
// '8BJX6BQNAH',
// '15YK9DQ237',
// '47RYF4RZ25',
// '49MZJYMYFG',
// '61JKTUW9EK',
// '65TGGK5HN3',
// '69A84XP41J',
// '81UQ1NP3M8',
// '92J4UWJ7HE',
// '92VB29589C',
// '92VRAT1Y33',
// '255PJE9EAW',
// '793PN2GP9Y',
// 'AU516XU3MC',
// 'AUAYLX4E54',
// 'B7BKX1YHW1',
// 'CJGVUG49Y7',
// 'CJQ5QJ6N6Y',
// 'DRAMCRP5JW',
// 'DT42A9SL9K',
// 'E4FTL7G9EH',
// 'ES9P5PNP6T',
// 'EW36Y5KAV1',
// 'F5Z92136HM',
// 'FZ5MNB8FSC',
// 'GEH4GMT278',
// 'H7T4ND3F9U',
// 'HSKXTJTK52',
// 'J53KJJF9BB',
// 'JJYYSK8BY1',
// 'K3PRT5LC3P',
// 'KE4GC2WZQ5',
// 'LRAUTUHAE1',
// 'LYLHD5WE39',
// 'M12QPGMMMG',
// 'MADR9E16TJ',
// 'MJF971NKG8',
// 'NY73ZQWK6D',
// 'P6EDVBFRAV',
// 'R2R7EJQ9ZA',
// 'RJRH5S447J',
// 'RRDZWBT99V',
// 'RREKGVK72Y',
// 'SZ1AJA9UPF',
// 'T6JC1ASQYB',
// 'WA4LE3RH9P',
// 'WDM1SEV4NF',
// 'WHYLMQZ3ED',
// 'WYUFM61Z2J',
// 'X2LYZNPYMN',
// 'XXD2AAYY7L',
// 'Y4R1STTZLW',
// 'ZVGYSG8GGW',
// 'ZWUK9SLY12',

// 2AQUAWORLD
// MAMPYTANIE
// 2REGULAMIN
// KKZKZFCCTD

const cardsSeed: Card[] = [
    {
        code: 'AU516XU3MC',
        withQuestion: true,
        uid: 'azurnoctis',
        image: 'azurnoctis',
        comment: '',
        collectedBy: {},
        name: 'Azurnoctis',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'magic-creatures',
        description: 'Fioletowy smok o rogach niczym szafirowe obeliski, skrzydła rozpostarte szeroko jak północne zorze, tchnienie zimne jak najgłębsze odmęty oceanu, spoglądający na świat z tajemniczą łagodnością.'
    },
    {
        code: 'AUAYLX4E54',
        withQuestion: true,
        uid: 'gryffindor',
        image: 'gryffindor',
        comment: '',
        collectedBy: {},
        name: 'Gryffindor',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'magic-creatures',
        description: 'Niczym płomień nadziei unosił się Feniks w locie, ożywiając niebo swym majestatycznym tańcem. Jego pióra świeciły sprawiedliwością, a opiekunem jego mocy był mędrzec Albus Dumbledore.'
    },
    {
        code: 'B7BKX1YHW1',
        withQuestion: false,
        uid: 'krasnogrzbiet',
        image: 'krasnogrzbiet',
        comment: '',
        collectedBy: {},
        name: 'Krasnogrzbiet',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'magic-creatures',
        description: 'Mała istota, zielona jak letnie liście, czuwa nad swoją jaskinią wśród rozkwitającej roślinności. Na jej grzbiecie rosło niewielkie drzewko, a jej obecność dodaje magii i harmonii temu malowniczemu zakątkowi.'
    },
    {
        code: 'CJGVUG49Y7',
        withQuestion: true,
        uid: 'caladrius',
        image: 'caladrius',
        comment: '',
        collectedBy: {},
        name: 'Caladrius',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'magic-creatures',
        description: 'Głęboko w lesie spotkałem Caladriusa. Jego pełne mądrości, pomarańczowe oczy spoglądały na mnie. Głosem ludzkim przedstawił się jako król i strażnik lasu.'
    },
    {
        code: 'CJQ5QJ6N6Y',
        withQuestion: true,
        uid: 'ravakai',
        image: 'ravakai',
        comment: '',
        collectedBy: {},
        name: 'Rava\'kai',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'magic-creatures',
        description: 'Dotarłem do Szafirowego jeziora i zobaczyłem statek w przystani. Rudy Khajiit, kapitan Rava\'kai, przywitał mnie na pokładzie. Jego kosztowny mundur i mądrość w oczach odzwierciedlały jego doświadczenie. Znalezienie tej przeprawy było darem niebios.'
    },
    {
        code: 'DRAMCRP5JW',
        withQuestion: false,
        uid: 'skoczek-jasnobrody',
        image: 'skoczek-jasnobrody',
        comment: '',
        collectedBy: {},
        name: 'Skoczek Jasnobrody',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'magic-creatures',
        description: 'Skoczek Jasnobrody, mały i czerwony, wywołał moje zainteresowanie swoją długą brodą. Był płochliwy, ale pełen uroku. Wydawał się niezbyt roztropny, lecz wzbudzał sympatię swoim niezwykłym wyglądem.'
    },
    {
        code: 'DT42A9SL9K',
        withQuestion: true,
        uid: 'flordraak',
        image: 'flordraak',
        comment: '',
        collectedBy: {},
        name: 'Flordraak',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'magic-creatures',
        description: 'Spokój wypełniał ogromną jaszczurkę, a na jej plecach rozkwitł las różowo-purpurowych kwiatów. Ignorowała moją obecność, wygrzewając się w zachodzącym słońcu nad Szafirowym Jeziorem.'
    },
    {
        code: 'E4FTL7G9EH',
        withQuestion: true,
        uid: 'erydor',
        image: 'erydor',
        comment: '',
        collectedBy: {},
        name: 'Erydor',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'magic-creatures',
        description: 'Między górskimi szczytami spotkałem słonia w królewskiej zbroi, który spokojnie pasł się w wąwozie. Czy był samotny, czy też strzegł tajemnic? Pozostałem w bezpiecznej odległości, by nie zakłócać jego spokoju.'
    },
    {
        code: 'ES9P5PNP6T',
        withQuestion: false,
        uid: 'gandalf',
        image: 'gandalf',
        comment: '',
        collectedBy: {},
        name: 'Gandalf',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'heroes',
        description: 'Wędrując napotkałem starca na białym koniu. Jego długa broda i mądrość w oczach sugerowały potężną obecność. Spojrzał na mnie, po czym spokojnie odjechał, jakby miał ważne zadanie do spełnienia.'
    },
    {
        code: 'EW36Y5KAV1',
        withQuestion: true,
        uid: 'ravenna',
        image: 'ravenna',
        comment: '',
        collectedBy: {},
        name: 'Ravenna',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'heroes',
        description: 'Zauważyłem Ravennę, czerwonowłosą kobietę o hipnotyzującym spojrzeniu. Jej intensywny wzrok zdradzał pożądanie - czyżby pragnęła skarbów, które ze sobą niosłem, czy może mego serca?'
    },
    {
        code: 'F5Z92136HM',
        withQuestion: true,
        uid: 'durngar',
        image: 'durngar',
        comment: '',
        collectedBy: {},
        name: 'Durngar',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'heroes',
        description: 'Durngar, złocisty wojownik z gór, był moim wiernym towarzyszem w podróży przez Srebrne Pustkowia ku legendarnemu Drzewu Życia w Erindar. Choć żegnaliśmy się na skraju tej krainy, nasze wspomnienia trwają.'
    },
    {
        code: 'FZ5MNB8FSC',
        withQuestion: false,
        uid: 'gordon',
        image: 'gordon',
        comment: '',
        collectedBy: {},
        name: 'Gordon',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'heroes',
        description: 'Na brzegu piaszczystej plaży spotkałem Gordona w jego charakterystycznym kombinezonie. Jego spojrzenie skierowane na ocean zdawało się szukać czegoś poza horyzontem - może kolejnej inwazji kosmitów?'
    },
    {
        code: 'GEH4GMT278',
        withQuestion: true,
        uid: 'spectrus',
        image: 'spectrus',
        comment: '',
        collectedBy: {},
        name: 'Spectrus',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'heroes',
        description: 'W centrum stalowego obozu, Spectrus, strażnik w kewlarowym pancerzu, zbliżył się do mnie z wyciągniętą bronią. Jego żółte oczy świeciły w mroku, jego postawa była wyraźnym ostrzeżeniem - nie chciał tutaj obcych.'
    },
    {
        code: 'H7T4ND3F9U',
        withQuestion: true,
        uid: 'aldric',
        image: 'aldric',
        comment: '',
        collectedBy: {},
        name: 'Aldric',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'heroes',
        description: 'Niezachwiany jak skała, Aldric był naszym przewodnikiem i tarczą. Był jak wieża w środku burzy, zawsze stanowiący punkt odniesienia, kiedy traciliśmy drogę. Jego odwaga i determinacja były naszym ostoją.'
    },
    {
        code: 'HSKXTJTK52',
        withQuestion: false,
        uid: 'alessia',
        image: 'alessia',
        comment: '',
        collectedBy: {},
        name: 'Alessia',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'heroes',
        description: 'Nasza waleczna towarzyszka poszukiwała relikwii z przeszłości - artefaktu o niezmierzonej mocy. Kiedy ostatecznie wyjawiła nam swój cel, zrozumieliśmy głębię jej determinacji.'
    },
    {
        code: 'J53KJJF9BB',
        withQuestion: true,
        uid: 'thalia',
        image: 'thalia',
        comment: '',
        collectedBy: {},
        name: 'Thalia',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'heroes',
        description: 'Thalia, dzika i tajemnicza, była naszym łącznikiem z naturą. Wierzyła w to, że nasza misja jest zgodna z wolą bogów ziemi i nieba. Jej duch przyrody napełniał nas nadzieją, nawet w najciemniejszych chwilach.'
    },
    {
        code: 'JJYYSK8BY1',
        withQuestion: true,
        uid: 'capstan',
        image: 'capstan',
        comment: '',
        collectedBy: {},
        name: 'Capstan',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'heroes',
        description: 'W gęstej dżungli spotkaliśmy kapitana Capstana na tratwie zbudowanej z wraku okrętu. Opowieści o tym samotnym, obłąkanym piracie od lat krążyły po okolicznych wioskach, ale nikt nie brał ich na poważnie.'
    },
    {
        code: 'K3PRT5LC3P',
        withQuestion: false,
        uid: 'pantheryx',
        image: 'pantheryx',
        comment: '',
        collectedBy: {},
        name: 'Pantheryx',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'darkest-night',
        description: 'Spotkanie z Pantheryx\'em jest jak przekleństwo - niewiele stworzeń przeżywa jego atak. W chwili spotkania, jego ofiary czują intensywny chłód, paraliżujący strach i po chwili wszystko, co zostaje, to cisza.'
    },
    {
        code: 'KE4GC2WZQ5',
        withQuestion: true,
        uid: 'montisaur',
        image: 'montisaur',
        comment: '',
        collectedBy: {},
        name: 'Montisaur',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'darkest-night',
        description: 'Znany również jako Górski Gigant. Na jego grzbiecie rosną drzewa, a jego przerażające ryki niosą się nocą z najwyższych szczytów. Wprawdzie niewiele osób miało okazję go zobaczyć, jednak każdy, kto usłyszał jego ryk, pamięta go na zawsze.'
    },
    {
        code: 'LRAUTUHAE1',
        withQuestion: true,
        uid: 'torfiaki',
        image: 'torfiaki',
        comment: '',
        collectedBy: {},
        name: 'Torfiaki',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'darkest-night',
        description: 'Duchy bagien Erindar, są mrożącymi krew w żyłach stworzeniami. Cienie, które lewitują nisko nad bagnami, potrafią przybierać dowolne formy, wprowadzając w błąd nieostrożnych wędrowców.'
    },
    {
        code: 'LYLHD5WE39',
        withQuestion: false,
        uid: 'templariusz',
        image: 'templariusz',
        comment: '',
        collectedBy: {},
        name: 'Templariusz',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'darkest-night',
        description: 'Nadejście Templariuszy Gildii Mroku zawsze zwiastuje mróz. Są okryci białymi szatami, symbolizującymi ich świętość, a ich broń - Voidorb, to wytwór niezgłębionej mocy, prawdziwa czarna dziura.'
    },
    {
        code: 'M12QPGMMMG',
        withQuestion: true,
        uid: 'warga',
        image: 'warga',
        comment: '',
        collectedBy: {},
        name: 'Warga',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'darkest-night',
        description: 'Te wilko-podobne bestie unikają większych grup ludzi, zazwyczaj polując na samotne ofiary. Ich obecność odcisnęła piętno na miejscowych legendach i powoduje, że nawet najodważniejsi podróżnicy starają się unikać okolic Szafirowego Jeziora.'
    },
    {
        code: 'MADR9E16TJ',
        withQuestion: true,
        uid: 'skala-starca',
        image: 'skala-starca',
        comment: '',
        collectedBy: {},
        name: 'Skała Starca',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'darkest-night',
        description: 'Aldric opowiadał o straszliwej Skale Starca. Mimo jej nieruchomości, oczy zdawały się żywe, podążając za każdym, kto ośmielił się zbliżyć. Może to być zaklęty człowiek lub demoniczna istota.'
    },
    {
        code: 'MJF971NKG8',
        withQuestion: false,
        uid: 'erindar',
        image: 'erindar',
        comment: '',
        collectedBy: {},
        name: 'Erindar',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'postcards-from-far-away',
        description: 'Erindar, ziemie tysiąca przepaści. Każdy tutejszy uskok stanowi ekosystem wypełniony bujnym, zielonym życiem, przerywanym tylko przez srebrzysty wstęgę leniwie płynących rzek.'
    },
    {
        code: 'NY73ZQWK6D',
        withQuestion: true,
        uid: 'lavendel',
        image: 'lavendel',
        comment: '',
        collectedBy: {},
        name: 'Lavendel',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'postcards-from-far-away',
        description: 'Znajdujemy się w Lavendel, wiosce o fioletowych dachach, ukrytej w sercu krainy Aquria. W tle majestatycznie wznosi się wieża Pałacu Gildii Wody, zwiastująca bliskość błękitnych wód oceanu.'
    },
    {
        code: 'P6EDVBFRAV',
        withQuestion: true,
        uid: 'tenchi',
        image: 'tenchi',
        comment: '',
        collectedBy: {},
        name: 'Świątynia Tenchi',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'postcards-from-far-away',
        description: 'Ta skromna świątynia żywo kontrastuje z otaczającą ją dziką przyrodą. Podobno kapitan Rava\'kai był tak oczarowany jej prostotą i spokojem, że spędził tam kilka dni, zamiast kontynuować swoją podróż na wschód.'
    },
    {
        code: 'R2R7EJQ9ZA',
        withQuestion: false,
        uid: 'cytadela',
        image: 'cytadela',
        comment: '',
        collectedBy: {},
        name: 'Cytadela Prądów',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'postcards-from-far-away',
        description: 'Niezdobyta twierdza, dumnie wznosząca się 500 metrów nad fale Oceanu Aqurii. Oznaka potęgi Gildii Wody, ta monumentalna konstrukcja jest jednak obiektem pragnień Templariuszy, którzy pragną przejąć kontrolę nad lokalnym handlem.'
    },
    {
        code: 'RJRH5S447J',
        withQuestion: true,
        uid: 'lumen-vitae',
        image: 'lumen-vitae',
        comment: '',
        collectedBy: {},
        name: 'Lumen Vitae',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'postcards-from-far-away',
        description: 'Monumentalne drzewo w sercu krainy Arcanum, jest miejscem zjawiskowego spektaklu światła podczas nocy nowiu. Choć wielu przybywa, aby podziwiać jego fioletowe blaski, tajemnicze zniknięcia w okolicy nadają miejscu mroczną aurę.'
    },
    {
        code: 'RRDZWBT99V',
        withQuestion: true,
        uid: 'valeria',
        image: 'valeria',
        comment: '',
        collectedBy: {},
        name: 'Valeria',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'galaxy',
        description: 'Void Wanderer powoli sunął przez próżnię gdy Valeria, żołnierz przypominający tajemniczego Spectrusa, z zaciekawieniem obserwowała nową planetę, Azura-9. Gotowa odkrywać, ale też bronić się, jeśli zajdzie taka potrzeba.'
    },
    {
        code: 'RREKGVK72Y',
        withQuestion: false,
        uid: 'echo',
        image: 'echo',
        comment: '',
        collectedBy: {},
        name: 'Echo',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'galaxy',
        description: 'Ta niewyobrażalna wyrwa, powstała w wyniku zjawiska zwanego "Echo Gwiazd". Pochodzi ono od nieznanej, silnej energii, która uderzyła w planetę, tworząc otwór niczym bramę do innego świata.'
    },
    {
        code: 'SZ1AJA9UPF',
        withQuestion: true,
        uid: 'zorza',
        image: 'zorza',
        comment: '',
        collectedBy: {},
        name: 'Zorza',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'galaxy',
        description: 'Obserwowana z "Neptun\'s Gaze", śmierć planety jest równie imponująca co jej życie. W mgnieniu oka wyrzuca na zewnątrz miliony ton gorącej, jasnej materii, rozświetlając kosmos błyskiem oślepiającej bieli.'
    },
    {
        code: 'T6JC1ASQYB',
        withQuestion: true,
        uid: 'portal',
        image: 'portal',
        comment: '',
        collectedBy: {},
        name: 'Portal',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'galaxy',
        description: 'Na ulicach New Theta życie momentalnie zamarło. Pojawiła się tajemnicza, stalowa brama, której krańce promieniowały niebieskim blaskiem, prowokując pytania - Gildia Mroku, czy coś nowego?'
    },
    {
        code: 'WA4LE3RH9P',
        withQuestion: false,
        uid: 'ksiezniczka',
        image: 'ksiezniczka',
        comment: '',
        collectedBy: {},
        name: 'Księżniczka',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'galaxy',
        description: 'W Gwiezdnej Bazie Orion, mała dziewczynka stała zasłuchana w pulsujący rytm portalu. Od dłuższego czasu obserwowała jego pojawienie, nieświadoma, że identyczne zjawisko zaistniało na ulicach New Theta.'
    },
    {
        code: 'WDM1SEV4NF',
        withQuestion: true,
        uid: 'ziggurat',
        image: 'ziggurat',
        comment: '',
        collectedBy: {},
        name: 'Ziggurat',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'galaxy',
        description: 'Wędrowiec stał w cieniu masywnej Wieży Ziggurat, siedziby Gildii Mroku. Ta monumentalna struktura miała wysokość kilku kilometrów i dominowała nad purpurowym pejzażem. Wszyscy, poza szaleńcami, unikali jej.'
    },
    {
        code: 'WHYLMQZ3ED',
        withQuestion: true,
        uid: 'przechadzka',
        image: 'przechadzka',
        comment: '',
        collectedBy: {},
        name: 'Przechadzka',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'steam-city',
        description: 'Kobieta przechadzała się wzdłuż ulic Miasta Pary, arcydzieła Gildii Stali. Ciepłe światło z sąsiedniego warsztatu oświetlało spokojną scenę, gdzie atmosfera była tak ciężka jak znużone powietrze miejskiego wieczoru.'
    },
    {
        code: 'WYUFM61Z2J',
        withQuestion: false,
        uid: 'skyliner',
        image: 'skyliner',
        comment: '',
        collectedBy: {},
        name: 'Skyliner',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'steam-city',
        description: 'Skyliner, majestatyczne dzieło Gildii Metalu, sunął po torach uniesionych dzięki technologii manipulacji grawitacją. Jego prędkość i wydajność zrewolucjonizowały transport towarów, łącząc odległe krainy jak nigdy dotąd.'
    },
    {
        code: 'X2LYZNPYMN',
        withQuestion: true,
        uid: 'tango',
        image: 'tango',
        comment: '',
        collectedBy: {},
        name: 'Tango',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'steam-city',
        description: 'Maszyna wojenna sunęła z impetem, zataczając ścieżki metalowymi gąsienicami. Bezpośrednio nad nią, samolot transportowy przelatywał tak nisko, że skrzydła niemal dotykały maszyny - pilotom Gildii Stali z pewnością nie brakowało odwagi.'
    },
    {
        code: 'XXD2AAYY7L',
        withQuestion: true,
        uid: 'architekt',
        image: 'architekt',
        comment: '',
        collectedBy: {},
        name: 'Architekt',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'steam-city',
        description: 'To dzięki niezwykle umiejętnym robotnikom Gildia Stali stała się potęgą, tworząc monumentalną architekturę, która przewyższała osiągnięcia Gildii Wody. Ich spawacze przyczynili się do kształtowania świata, jaki znamy.'
    },
    {
        code: 'Y4R1STTZLW',
        withQuestion: false,
        uid: 'tesla',
        image: 'tesla',
        comment: '',
        collectedBy: {},
        name: 'Nikolaj Tesla',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'steam-city',
        description: 'Założyciel Gildii Stali, Tesla, był prawdziwym wizjonerem. Jego wybitne umiejętności i wiedza z dziedziny technologii i metalurgii doprowadziły do powstania niesamowitego Miasta Pary.'
    },
    {
        code: 'ZVGYSG8GGW',
        withQuestion: true,
        uid: 'miasto-pary',
        image: 'miasto-pary',
        comment: '',
        collectedBy: {},
        name: 'Miasto Pary',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'steam-city',
        description: 'Z ratusza rozpościerał się widok na Miasto Pary - stalowe wieże i szklane kopuły tworzyły niezwykłe krajobrazy steampunkowej metropolii. Jedyne dźwięki dochodziły od rzeki Flux, której cichy szum wypełniał poranne powietrze.'
    },
    {
        code: 'ZWUK9SLY12',
        withQuestion: true,
        uid: 'aloy',
        image: 'aloy',
        comment: '',
        collectedBy: {},
        name: 'Aloy',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'from-the-past',
        description: 'Aloy pod opieką Rosta z dnia na dzień zasilała swoją wiedzę o dziczy i mechanicznych stworach. Pomimo wygnania z Nora, jej determinacja i niezłomność były zwiastunami przyszłego przeznaczenia - odkrycia prawdy o swoim świecie i stawienia czoła niebezpieczeństwom.'
    },
    {
        code: '3M3SJZDVFV',
        withQuestion: false,
        uid: 'sparrow',
        image: 'sparrow',
        comment: '',
        collectedBy: {},
        name: 'Sparrow',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'from-the-past',
        description: 'Młody Sparrow, wychowany w portach Karaibów, szybko nauczył się trudów i radości pirackiego życia. Jego spryt, wdzięk i niezdyscyplinowany duch były zapowiedzią niezwykłych przygód i legendarnego statusu kapitana pirackiego okrętu.'
    },
    {
        code: '3U1XSSBMNF',
        withQuestion: true,
        uid: 'shepard',
        image: 'shepard',
        comment: '',
        collectedBy: {},
        name: 'Shepard',
        isActive: true,
        tier: CardTier.LEGENDARY,
        value: CardTierValue.LEGENDARY,
        cardSet: 'from-the-past',
        description: 'Młody Shepard, zawsze marzył o przestworzach. Jego wczesne zainteresowanie taktyką i wojskową dyscypliną stało się podwaliną dla przyszłego kapitana Normandii i obrońcy galaktyki.'
    },
    {
        code: '3X8RN3R4MS',
        withQuestion: true,
        uid: 'kratos',
        image: 'kratos',
        comment: '',
        collectedBy: {},
        name: 'Kratos',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'from-the-past',
        description: 'Młody Kratos, ukształtowany przez surowe dyscypliny Sparty, od wczesnych lat wykazywał oznaki nieustraszonej siły i zaciętości. Przeznaczony do walki, jego brutalna natura przepowiadała przyszłość Boga Wojny.'
    },
    {
        code: '3ZMQQLLWWX',
        withQuestion: false,
        uid: 'hermiona',
        image: 'hermiona',
        comment: '',
        collectedBy: {},
        name: 'Hermiona',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'from-the-past',
        description: 'Przed otrzymaniem listu z Hogwartu, młoda Pani Granger była typowym, ambitnym dzieckiem mugoli. W dzieciństwie zawsze była ciekawa świata, co przełożyło się na jej pasję do nauki magii.'
    },
    {
        code: '4GYYPTLSYH',
        withQuestion: true,
        uid: 'suweren',
        image: 'suweren',
        comment: '',
        collectedBy: {},
        name: 'Suweren',
        isActive: true,
        tier: CardTier.EPIC,
        value: CardTierValue.EPIC,
        cardSet: 'nebula',
        description: 'Spokojna suwerenka Gildii Mroku zwraca się ku kosmicznej nicości. Gniew, którego ucieleśnieniem jest Voidorb, kryje się za jej spokojem.'
    },
    {
        code: '4J6KBCCHW1',
        withQuestion: true,
        uid: 'feline',
        image: 'feline',
        comment: '',
        collectedBy: {},
        name: 'Spectral Feline',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'nebula',
        description: 'Spectral Feline to abstrakcyjne odzwierciedlenie wojowniczego ducha - oczy różnych kolorów spoglądają w przyszłość, a świetliste paski to ślady walki.'
    },
    {
        code: '5DEYQBVWBP',
        withQuestion: false,
        uid: 'nocturne',
        image: 'nocturne',
        comment: '',
        collectedBy: {},
        name: 'Rainbow Nocturne',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'nebula',
        description: 'Ta Sowa, nazwana Rainbow Nocturne, wydaje się być utkana z tęczy. Różnokolorowe oczy wpatrują się głęboko, a skrzydła rozpoczynają wizualną symfonię'
    },
    {
        code: '6KVTS4ZFKC',
        withQuestion: true,
        uid: 'lupus',
        image: 'lupus',
        comment: '',
        collectedBy: {},
        name: 'Prismatic Lupus',
        isActive: true,
        tier: CardTier.RARE,
        value: CardTierValue.RARE,
        cardSet: 'nebula',
        description: 'Prismatic Lupus, Wilk o wielobarwnej głowie, to obraz niezłomnej siły. Jego oczy są jak gwiazdy, a głowa mieni się jak kosmiczny kalejdoskop.'
    },
    {
        code: '6PZJA4AGP3',
        withQuestion: true,
        uid: 'serpent',
        image: 'serpent',
        comment: '',
        collectedBy: {},
        name: 'Steel Serpent',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'nebula',
        description: 'Steel Serpent, Wąż o różnobarwnych oczach i ciele, to wizualna interpretacja zmiany. Każda zmiana koloru to nowe doświadczenie w jego bezkresnym życiu.'
    },
    {
        code: '2AQUAWORLD',
        withQuestion: false,
        uid: 'guild-water',
        image: 'guild-water',
        comment: '',
        collectedBy: {},
        name: 'Gildia Wody',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'secret',
        description: 'Morscy kupcy kontrolujący oceaniczne szlaki. Ich zasoby i bogactwa są legendą, a neutralność - ich tarczą. Handel to ich pasja i broń, której używają do utrzymania równowagi wobec innych gildii.'
    },
    {
        code: 'MAMPYTANIE',
        withQuestion: false,
        uid: 'guild-steel',
        image: 'guild-steel',
        comment: '',
        collectedBy: {},
        name: 'Gildia Stali',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'secret',
        description: 'Architekci postępu, trzymający w rękach klucze do przemysłowego triumfu. Pragną zdominować Erindar i jego zasoby, aby rozpalić ogniska ich stalowych miast i maszyn. Nie cofną się przed niczym.'
    },
    {
        code: '2REGULAMIN',
        withQuestion: false,
        uid: 'guild-void',
        image: 'guild-void',
        comment: '',
        collectedBy: {},
        name: 'Gildia Mroku',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'secret',
        description: 'Mroczni magowie, wykorzystujący kosmiczną moc. Ich obecność to zimne ostrze, a ich Voidorb - narzędzie dominacji. Kontrola świata jest ich ostatecznym celem, a tajemnicza moc jest ich bronią.'
    },
    {
        code: 'KKZKZFCCTD',
        withQuestion: false,
        uid: 'guild-desert',
        image: 'guild-desert',
        comment: '',
        collectedBy: {},
        name: 'Gildia Pustyni',
        isActive: true,
        tier: CardTier.COMMON,
        value: CardTierValue.COMMON,
        cardSet: 'secret',
        description: 'Bohaterowie pustyni, kultywujący moc wiatru i słońca. W pogoni za utrzymaniem swojego surowego, ale ukochanego domu, ich celem jest zniszczenie tamy Gildii Stali, która pochłania ich zasoby wodne.'
    }
];

export default cardsSeed;
